# Generated by Django 4.2.6 on 2024-04-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teacherschool_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacherschool')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddField(
            model_name='topic',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notes'),
        ),
    ]
