# Generated by Django 4.2.6 on 2023-11-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_topic_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics', to='api.subject'),
        ),
    ]
