# Generated by Django 4.2.6 on 2023-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subtopic_content_alter_topic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
