# Generated by Django 4.2.6 on 2024-04-27 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentnoteslog_studentschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnoteslog',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topic'),
        ),
    ]
