# Generated by Django 4.2.6 on 2023-11-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_subtopic_content2_alter_subtopic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'order')},
        ),
    ]
