# Generated by Django 4.2.6 on 2023-11-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_choice_text_alter_question_text_and_more'),
        ('api', '0012_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('question', 'student', 'choice')},
        ),
    ]
