# Generated by Django 4.2.6 on 2024-05-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notes_introduction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicquestionstudentanswer',
            unique_together={('topic_question', 'student')},
        ),
    ]
