# Generated by Django 4.2.6 on 2024-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_topicquestionstudentanswer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttopicprogress',
            unique_together={('student', 'topic')},
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.RemoveField(
            model_name='studenttopicprogress',
            name='subject',
        ),
    ]
