# Generated by Django 4.2.6 on 2023-11-29 05:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=api.models.Topic.get_next_topic_order),
        ),
    ]
