# Generated by Django 4.2.6 on 2024-05-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_studentnoteslog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentnoteslog',
            unique_together={('topic', 'student', 'note')},
        ),
    ]
