# Generated by Django 4.2.6 on 2024-02-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
