# Generated by Django 4.2.6 on 2023-11-11 01:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
