# Generated by Django 4.2.6 on 2024-02-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=60),
        ),
    ]
