# Generated by Django 4.2.6 on 2024-02-10 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_created_at_question_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
