# Generated by Django 4.2.6 on 2024-02-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_exam_created_at_exam_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=3600),
        ),
    ]
