# Generated by Django 4.2.6 on 2024-02-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=120),
        ),
    ]
