# Generated by Django 4.2.6 on 2024-02-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_examanswer_answer_alter_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
