# Generated by Django 4.2.6 on 2024-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_examanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
