# Generated by Django 4.2.6 on 2024-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_examanswer_comment_examanswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
