# Generated by Django 4.2.6 on 2024-04-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_topic_unique_together_teachersubject_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teachersubject'),
        ),
    ]
