# Generated by Django 4.2.6 on 2024-05-02 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_topicquestion_topicquestionstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='topicquestion',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicquestion',
            name='mark',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topicquestion',
            name='time',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='api.question'),
        ),
    ]
