# Generated by Django 4.2.6 on 2024-05-02 04:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_topicquestion_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquestion',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
