# Generated by Django 4.2.6 on 2024-05-02 05:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_topicquestion_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('topic_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_question_choices', to='api.topicquestion')),
            ],
        ),
    ]
