# Generated by Django 4.2.6 on 2024-05-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_topicquestionchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicQuestionStudent',
            new_name='TopicQuestionStudentAnswer',
        ),
    ]
