# Generated by Django 4.2.6 on 2024-05-04 02:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_topicquestionstudent_topicquestionstudentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='introduction',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topicquestionchoice',
            name='topic_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='api.topicquestion'),
        ),
    ]
