# Generated by Django 4.2.6 on 2024-05-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_studentnoteslog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level'),
        ),
    ]
