# Generated by Django 4.2.6 on 2024-05-06 05:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_topic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
