# Generated by Django 4.2.6 on 2024-05-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_subtopic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
