# Generated by Django 4.2.6 on 2024-05-07 11:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_subtopic_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='test',
        ),
        migrations.AddField(
            model_name='topic',
            name='introduction',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        # migrations.AddField(
        #     model_name='topicquestion',
        #     name='test',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.test'),
        # ),
    ]
