# Generated by Django 4.2.6 on 2024-05-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
